worker_processes auto;

events {
    worker_connections 1024;
}

http {
    charset utf-8;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on; 
    keepalive_timeout 65;
    proxy_cache_path /var/cache/nginx/stats_cache
        levels=1:2           
        keys_zone=stats_cache:10m
        max_size=50m
        inactive=60m
        use_temp_path=off;

    upstream backend {
        server api-a:3000;
        server api-b:3000;
    } #automatycznie robi load balancing

    server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/stats {
        proxy_pass http://backend/stats;
        #proxy_pass http://backend:3000/stats;
        proxy_cache stats_cache;
        proxy_cache_valid 200 30s;
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /api/ {
        proxy_pass http://backend/;
        #proxy_pass http://backend:3000/;
    }
}
}